const POST_STUDENT_PROFILE_EXPERIENCE_REQUEST =  "postStudentProfileExperienceRequest";
const POST_STUDENT_PROFILE_EXPERIENCE_RESPONSE = "postStudentProfileExperienceResponse";
const POST_STUDENT_PROFILE_REQUEST =  "postStudentProfileRequest";
const POST_STUDENT_PROFILE_RESPONSE = "postStudentProfileResponse";
const GET_STUDENT_PROFILE_REQUEST =  "getStudentProfileRequest";
const GET_STUDENT_PROFILE_RESPONSE = "getStudentProfileResponse";
const UPDATE_STUDENT_PROFILE_OBJECTIVE_REQUEST =  "updateStudentProfileObjectiveRequest";
const UPDATE_STUDENT_PROFILE_OBJECTIVE_RESPONSE = "updateStudentProfileObjectiveResponse";
const UPDATE_STUDENT_PROFILE_SKILLSET_REQUEST =  "updateStudentProfileSkillSetRequest";
const UPDATE_STUDENT_PROFILE_SKILLSET_RESPONSE = "updateStudentProfileSkillSetResponse";
const UPDATE_STUDENT_PROFILE_CITY_REQUEST =  "updateStudentProfileCityRequest";
const UPDATE_STUDENT_PROFILE_CITY_RESPONSE = "updateStudentProfileCityResponse";
const MESSAGE_REQUEST = "messageRequest";
const MESSAGE_RESPONSE = "messageResponse";
const GET_MESSAGE_REQUEST = "getMessageRequest";
const GET_MESSAGE_RESPONSE = "getMessageResponse";
const GET_ALL_STUDENTS_REQUEST = "getAllStudentsRequest";
const GET_ALL_STUDENTS_RESPONSE = "getAllStudentsResponse";
const POST_COMPANY_PROFILE_RESPONSE = "postCompanyProfileResponse";
const POST_COMPANY_PROFILE_REQUEST = "postCompanyProfileRequest";
const POST_JOB_RESPONSE = "postJobResponse";
const POST_JOB_REQUEST = "postJobRequest";
const ALL_JOBS_RESPONSE = "getAllJobsResponse";
const ALL_JOBS_REQUEST = "getAllJobsRequest";
const ALL_JOB_OPENINGS_RESPONSE = "getAllJobOpeningsResponse";
const ALL_JOB_OPENINGS_REQUEST = "getAllJobOpeningsRequest";
const GET_COMPANY_DETAILS_RESPONSE = "getCompanyDetailsResponse";
const GET_COMPANY_DETAILS_REQUEST = "getCompanyDetailsRequest";
const POST_APPLY_JOB_RESPONSE = "postApplyJobResponse";
const POST_APPLY_JOB_REQUEST = "postApplyJobRequest";
const GET_APPLICANT_DETAILS_REQUEST = "getApplicantDetailsRequest";
const GET_APPLICANT_DETAILS_RESPONSE = "getApplicantDetailsResponse";
const UPDATE_APPLICATION_STATUS_REQUEST = "updateApplicationStatusRequest";
const UPDATE_APPLICATION_STATUS_RESPONSE = "updateApplicationStatusResponse";



module.exports = {
    UPDATE_APPLICATION_STATUS_REQUEST,
    UPDATE_APPLICATION_STATUS_RESPONSE,
    GET_APPLICANT_DETAILS_REQUEST,
    GET_APPLICANT_DETAILS_RESPONSE,
    POST_APPLY_JOB_REQUEST,
    POST_APPLY_JOB_RESPONSE,
    GET_COMPANY_DETAILS_RESPONSE,
    GET_COMPANY_DETAILS_REQUEST,
    ALL_JOB_OPENINGS_RESPONSE,
    ALL_JOB_OPENINGS_REQUEST,
    ALL_JOBS_RESPONSE,
    ALL_JOBS_REQUEST,
    POST_JOB_REQUEST,
    POST_JOB_RESPONSE,
    GET_ALL_STUDENTS_REQUEST,
    GET_ALL_STUDENTS_RESPONSE,
    POST_STUDENT_PROFILE_REQUEST,
    POST_STUDENT_PROFILE_RESPONSE,
    POST_STUDENT_PROFILE_EXPERIENCE_REQUEST,
    POST_STUDENT_PROFILE_EXPERIENCE_RESPONSE,
    GET_STUDENT_PROFILE_REQUEST,
    GET_STUDENT_PROFILE_RESPONSE,
    UPDATE_STUDENT_PROFILE_OBJECTIVE_REQUEST,
    UPDATE_STUDENT_PROFILE_OBJECTIVE_RESPONSE,
    UPDATE_STUDENT_PROFILE_SKILLSET_REQUEST,
    UPDATE_STUDENT_PROFILE_SKILLSET_RESPONSE,
    UPDATE_STUDENT_PROFILE_CITY_REQUEST,
    UPDATE_STUDENT_PROFILE_CITY_RESPONSE,
    MESSAGE_REQUEST,
    MESSAGE_RESPONSE,
    GET_MESSAGE_REQUEST,
    GET_MESSAGE_RESPONSE,
    POST_COMPANY_PROFILE_RESPONSE,
    POST_COMPANY_PROFILE_REQUEST
};


